repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: "business-facing/layer"
      - id: trailing-whitespace
        exclude: "business-facing/layer"
      - id: check-yaml
        exclude: "business-facing/layer"
      - id: check-json
        exclude: "business-facing/layer"

  - repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.12.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        types: [ python ]
        files: ^src/

      # Run the formatter.
      - id: ruff-format
        types: [ python ]
        files: ^src/
