services:
  db_air:
    container_name: db_container
    image: postgis/postgis:16-3.5
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    networks:
      - net

  redis_app:
    image: redis
    command: --port 6379
    expose:
      - 6379
    restart: always
    networks:
      - net

  app:
    build:
      dockerfile: ./Dockerfile
    command: [ "/app/docker/app.sh" ]
    expose:
      - 8000
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data:/app/data
    depends_on:
      - db_air
      - redis_app
    networks:
      - net

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./var/log/nginx:/var/log/nginx
      - ./static:/usr/share/nginx/html/static
      - ./nginx/ssl/live/airportcards.ru:/etc/nginx/ssl  # Монтируем сертификаты напрямую
      - ./nginx/well-known:/usr/share/nginx/html/.well-known/acme-challenge
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    networks:
      - net

  celery:
    build:
      context: .
    env_file:
      - .env
    container_name: celery_app
    command: ["/app/docker/celery.sh", "celery"] # запуск скрипта для запуска celery
    depends_on:
      - redis
    networks:
      - net


  flower:
    build:
      context: .
    env_file:
      - .env
    container_name: flower_app
    command: ["/app/docker/celery.sh", "flower"]  # запуск скрипта для запуска flower
    depends_on:
      - redis
      - celery
    ports:
      - 5555:5555
    networks:
      - net


#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - ./nginx/ssl:/etc/letsencrypt  # Сохраняем сертификаты в ./nginx/ssl
#      - ./nginx/well-known:/usr/share/nginx/html/.well-known/acme-challenge
#    command: certonly --webroot --agree-tos --email frex@mail.ru --webroot-path /usr/share/nginx/html -d airportcards.ru -d www.airportcards.ru
#    depends_on:
#      - nginx
#    networks:
#      - net

volumes:
  postgres_volume:
  data:

networks:
  net:
    driver: bridge
