services:
  db_airport:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    networks:
      - net

  redis_app:
    image: redis
    command: --port 6379
    expose:
      - 6379
    networks:
      - net

  app:
    build:
      dockerfile: ./Dockerfile
    command: ["docker/app.sh"]
    expose:
      - 8000
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env
    depends_on:
      - db_airport
      - redis_app
    networks:
      - net

  nginx:
    container_name: airport-nginx
    build: ./nginx
    volumes:
      - ./var/log/nginx:/var/log/nginx
      - ./static:/usr/share/nginx/html/static
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - net

volumes:
  postgres_volume:

networks:
  net:
    driver: bridge