"""add table citys

Revision ID: 64c2a98ffef8
Revises: 9d04e08b84cd
Create Date: 2025-07-11 09:09:34.543014

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64c2a98ffef8"
down_revision: Union[str, None] = "9d04e08b84cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "citys",
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_users_city_hash",
        "citys",
        ["city"],
        unique=False,
        postgresql_using="hash",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_users_city_hash", table_name="citys", postgresql_using="hash")
    op.drop_table("citys")
    # ### end Alembic commands ###
